version: 2.1
jobs:
  build:
    resource_class: large
    machine:
      image: 'ubuntu-2004:202107-02'
    working_directory: ~/terraform-provider-watchtower
    steps:
    - add_ssh_keys:
        fingerprints:
        # hc-github-team-secure-boundary github user,TF_ACC=1 ~/.go/bin/go test ./... -v $(TESTARGS) -timeout 120m to read private modules
          - "d4:7f:b2:f7:6f:4d:e7:21:cc:d2:b7:6a:8b:68:e6:d4"
    - checkout
    - run:
        name: "Install go"
        command: |
          unset GOPATH # ci image has done strange things with GOPATH, unset it so install-go can fix it
          make install-go
          source ~/.bashrc
          go mod download
    - run:
        name: "Initialize Test Database"
        command: |
          sudo apt-get update && sudo apt-get install -y postgresql-client jq
          source ~/.bashrc
          make test-database-up
          until pg_isready -h 127.0.0.1; do docker container inspect boundary-sql-tests &> /dev/null || exit -1; sleep 1; done
    - run:
        name: "Run Acceptance Tests"
        command: |
          source ~/.bashrc
          make testacc-ci
    - run:
        name: "Cleanup"
        when: always
        command: |
          make test-database-down
